all:
  hosts:
    server:
      ansible_host: 192.168.27.150
      ansible_port: 22
      ansible_private_key_file: .vagrant/machines/server/virtualbox/private_key
    replica:
      ansible_host: 192.168.27.151
      ansible_port: 22
      ansible_private_key_file: .vagrant/machines/replica/virtualbox/private_key
    backup:
      ansible_host: 192.168.27.152
      ansible_port: 22
      ansible_private_key_file: .vagrant/machines/backup/virtualbox/private_key
